[tool.poetry]
name = "koji-fedmsg-plugin"
version = "0.1.0"
description = "Koji plugin to send messages on fedora-messaging"
authors = ["Fedora Infrastructure <admin@fedoraproject.org>"]
license = "GPL-3.0-or-later"
repository = "https://pagure.io/koji-fedmsg-plugin"
homepage = "https://pagure.io/koji-fedmsg-plugin"

[tool.poetry.plugins."fedora.messages"]
"buildsys.repo.done"="koji_fedmsg_plugin.messages.repo:DoneV1"
"buildsys.repo.init"="koji_fedmsg_plugin.messages.repo:InitV1"
"buildsys.tag"="koji_fedmsg_plugin.messages.tag:TagV1"
"buildsys.untag"="koji_fedmsg_plugin.messages.tag:UntagV1"
"buildsys.build.state.change"="koji_fedmsg_plugin.messages.build:BuildStateChangeV1"
"buildsys.package.list.change"="koji_fedmsg_plugin.messages.package:ListChangeV1"
"buildsys.rpm.sign"="koji_fedmsg_plugin.messages.rpm:SignV1"
"buildsys.task.state.change"="koji_fedmsg_plugin.messages.task:TaskStateChangeV1"

[tool.poetry.dependencies]
python = "^3.6"
fedora_messaging = "^2.0.1"
koji = "^1.20.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
sphinx = "^2.4.4"
flake8 = "^3.7.9"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
