[tool.poetry]
name = "koji-fedmsg-plugin"
version = "0.1.0"
description = "Koji plugin to send messages on fedora-messaging"
authors = ["Fedora Infrastructure <admin@fedoraproject.org>"]
license = "GPL-3.0-or-later"
repository = "https://pagure.io/koji-fedmsg-plugin"
homepage = "https://pagure.io/koji-fedmsg-plugin"

[tool.poetry.dependencies]
fedora_messaging = "^2.0.1"
koji = "^1.20.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
